version: '3.8'
services:
  database:
    image: bitnami/postgresql:13.3.0
    container_name: postgresql
    env_file: ".env"
    user: root
    volumes:
      - ./psql_data:/docker-entrypoint-initdb.d
      - ./psql_data/psql_volume:/bitnami/postgresql
    expose:
      - 5432
    ports:
      - 5454:5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRESQL_POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - localhost
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    expose:
      - 5050
    ports:
      - "5050:80"
    networks:
      - localhost
    depends_on:
      - database
    restart: always
  backend:
    container_name: uvicorn-fastapi
    build: ./app
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
      - database
    restart: always
    networks:
      - localhost
  scheduler:
    container_name: scheduler
    build: ./app
    command: python services/scheduler.py
    depends_on:
      - database
    restart: always
    networks:
      - localhost
networks:
  localhost:
    driver: bridge